"""Group-related database functions.

Current implementation is delegated to the legacy monolith module.
"""

from app.db.db_repo import (
    add_group_membership,
    create_group,
    create_group_request,
    create_group_role_request,
    delete_group,
    get_admin_notification_recipients,
    get_group_admins,
    get_group_members,
    get_group_membership_role,
    get_group_name,
    get_group_request,
    get_group_role_request,
    has_pending_group_request,
    has_pending_group_role_request,
    is_group_admin,
    list_all_groups,
    list_group_admin_users,
    list_group_viewer_users,
    list_pending_group_requests,
    list_pending_group_role_requests,
    remove_user_from_group,
    set_group_request_status,
    set_group_role_request_status,
    update_group_membership_role,
    user_in_group,
)

__all__ = [
    "add_group_membership",
    "create_group",
    "create_group_request",
    "create_group_role_request",
    "delete_group",
    "get_admin_notification_recipients",
    "get_group_admins",
    "get_group_members",
    "get_group_membership_role",
    "get_group_name",
    "get_group_request",
    "get_group_role_request",
    "has_pending_group_request",
    "has_pending_group_role_request",
    "is_group_admin",
    "list_all_groups",
    "list_group_admin_users",
    "list_group_viewer_users",
    "list_pending_group_requests",
    "list_pending_group_role_requests",
    "remove_user_from_group",
    "set_group_request_status",
    "set_group_role_request_status",
    "update_group_membership_role",
    "user_in_group",
]
