"""Repository facades used by application services."""

from app.repositories.absences_repo import get_absence_with_user, list_absences_for_period, list_pending_absences
from app.repositories.groups_repo import (
    get_group_admins,
    get_group_members,
    get_group_membership_role,
    get_group_name,
    list_all_groups,
    list_pending_group_requests,
)
from app.repositories.users_repo import (
    get_admins,
    get_all_users,
    get_approved_users,
    get_last_group_id,
    get_superadmin_group_notification_ids,
    get_superadmin_notification_mode,
    get_user_group_ids,
    get_user_groups,
    get_user_name_and_username,
    get_user_fullname,
    is_user_admin,
    is_user_approved,
    list_pending_user_ids,
    set_last_group_id,
    user_exists_in_db,
)

__all__ = [
    "get_absence_with_user",
    "get_admins",
    "get_all_users",
    "get_approved_users",
    "get_group_admins",
    "get_group_members",
    "get_group_membership_role",
    "get_group_name",
    "get_last_group_id",
    "get_superadmin_group_notification_ids",
    "get_superadmin_notification_mode",
    "get_user_group_ids",
    "get_user_groups",
    "get_user_name_and_username",
    "get_user_fullname",
    "is_user_admin",
    "is_user_approved",
    "list_all_groups",
    "list_absences_for_period",
    "list_pending_absences",
    "list_pending_group_requests",
    "list_pending_user_ids",
    "set_last_group_id",
    "user_exists_in_db",
]
